Added first draft of python wheel documentation
carla-simulator/carla pull request #4325
Opened 2021-06-21 11:05 UTC by corkyw10

## Python Wheel Documentation

I have written the first draft of the Python Wheel documentation. I have included sections that tell the user how `.egg` files were used prior to versions 0.9.12 and to select the right documentation for the version being used if necessary. 

Since the wheel is only supported in Ubuntu 18.04+ I have removed the sections that refer to separate packages that need to be installed for previous Ubuntu versions in the Linux build docs. Please double check this section in case the previous information is still needed.

Auditwheel may not be required as a dependency, this can be removed if needed.

2021-06-30 15:39 UTC, joel-mb requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @corkyw10)

___
*[Docs/build_linux.md, line 26 at r1](https://reviewable.io/reviews/carla-simulator/carla/4325#-McjJDF0A7pDkBGxBQqe:-McjJDF0A7pDkBGxBQqf:b-tmrbcy) ([raw file](https://github.com/carla-simulator/carla/blob/7aa51335dbfb823491bf4b79d510be00da859628/Docs/build_linux.md#L26)):*
> ```
> * __Ubuntu 18.04+.__ CARLA versions 0.9.12+ require a Linux system that uses a version of __glibc >= 2.27__.
> ```
With the last changes, I think we should not modify this section. The transition from eggs to wheels doesn't affect this.

When building from source, the previous requisites are still valid.
The `glibc>=2.27` requirement applies when installing the distributed Python client. Our Jenkins machine is using Ubuntu 18.04 and we will distribute the CARLA wheels targeting the `manylinux_2_27_x86_64` platform tag. Therefore, `pip install carla` will only work in Linux distros with`gibc>=2.27`. When building from source everything should remain the same.
___
*[Docs/build_linux.md, line 208 at r1](https://reviewable.io/reviews/carla-simulator/carla/4325#-McjQlIrB7tl_NJUQ5wt:-McjQlIsAdJCRqC_x4lH:b-19kixg) ([raw file](https://github.com/carla-simulator/carla/blob/7aa51335dbfb823491bf4b79d510be00da859628/Docs/build_linux.md#L208)):*
> ```
> Previous versions of CARLA created a `.egg` file containing the CARLA client library. __In versions 0.9.12+ this behavior changes significantly; `.egg` files are no longer used.__ `make PythonAPI` will install the library using `pip` and a `.whl` file. Every time you run `make PythonAPI` the previous library you had installed will be uninstalled and a new one will be installed according to the source code you are using.
> ```
Now it is possible to change this behaviour. I've added a couple of arguments to the `make PythonAPI` command:
* `--no-install-wheel`. If specified, doesn't install the wheel. By default this is `False`
* `--target-wheel-platform`. If specified, we try to repair the wheel with `auditwheel` targeting this platform.
___
*[Docs/build_system.md, line 81 at r1](https://reviewable.io/reviews/carla-simulator/carla/4325#-McjLFl_9SIYVGmehIIA:-McjLFl_9SIYVGmehIIB:byxh89x) ([raw file](https://github.com/carla-simulator/carla/blob/7aa51335dbfb823491bf4b79d510be00da859628/Docs/build_system.md#L81)):*
> ```
> Compiled using Python's `setuptools` ("setup.py"). Currently requires the following to be installed in the machine: Python, libpython-dev, and
> libboost-python-dev, pip>=20.3, wheel and auditwheel.
> ```
I think we can remove `libboost-python-dev` from this list as we are building it from source. @bernatx can you confirm that?


<!-- Sent from Reviewable.io -->

2021-07-13 10:44 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_linux.md, line 26 at r1](https://reviewable.io/reviews/carla-simulator/carla/4325#-McjJDF0A7pDkBGxBQqe:-MeUSyk25-J8tHirv1oF:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7aa51335dbfb823491bf4b79d510be00da859628/Docs/build_linux.md#L26)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> * __Ubuntu 18.04+.__ CARLA versions 0.9.12+ require a Linux system that uses a version of __glibc >= 2.27__.
> ```
With the last changes, I think we should not modify this section. The transition from eggs to wheels doesn't affect this.

When building from source, the previous requisites are still valid.
The `glibc>=2.27` requirement applies when installing the distributed Python client. Our Jenkins machine is using Ubuntu 18.04 and we will distribute the CARLA wheels targeting the `manylinux_2_27_x86_64` platform tag. Therefore, `pip install carla` will only work in Linux distros with`gibc>=2.27`. When building from source everything should remain the same.
</blockquote></details>

Done.
___
*[Docs/build_linux.md, line 208 at r1](https://reviewable.io/reviews/carla-simulator/carla/4325#-McjQlIrB7tl_NJUQ5wt:-MeUSxbM-u8FefHorTYl:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/7aa51335dbfb823491bf4b79d510be00da859628/Docs/build_linux.md#L208)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Previous versions of CARLA created a `.egg` file containing the CARLA client library. __In versions 0.9.12+ this behavior changes significantly; `.egg` files are no longer used.__ `make PythonAPI` will install the library using `pip` and a `.whl` file. Every time you run `make PythonAPI` the previous library you had installed will be uninstalled and a new one will be installed according to the source code you are using.
> ```
Now it is possible to change this behaviour. I've added a couple of arguments to the `make PythonAPI` command:
* `--no-install-wheel`. If specified, doesn't install the wheel. By default this is `False`
* `--target-wheel-platform`. If specified, we try to repair the wheel with `auditwheel` targeting this platform.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 14:49 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @corkyw10)

___
*[Docs/build_linux.md, line 68 at r3](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfYFfaC5MUPKmtMKEFp:-MfYFfaC5MUPKmtMKEFq:bi21ev0) ([raw file](https://github.com/carla-simulator/carla/blob/1f84becd864ea93cfa6050e61f87b07ceb057b3e/Docs/build_linux.md#L68)):*
> ```
> CARLA requires some Python dependencies to be installed with `pip version >= 20.3`.
> ```
The dependencies are not required to be installed with pip>=20.3. pip>=20.3 is necessary to install the CARLA PythonAPI with pip. I think it is fine to say here to update pip to 20.3 or greater. But maybe omit the part  `CARLA requires some Python dependencies to be installed with pip version >= 20.3`. Also it would be necessary to update `pip3`
___
*[Docs/build_linux.md, line 223 at r3](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfYH30d1b10ZdlEUAHn:-MfYH30d1b10ZdlEUAHo:bq0bk0p) ([raw file](https://github.com/carla-simulator/carla/blob/1f84becd864ea93cfa6050e61f87b07ceb057b3e/Docs/build_linux.md#L223)):*
> ```
> Every time you run `make PythonAPI` a `.whl` file containing the CARLA client library will be built and installed for your system. This `.whl` cannot be distributed as it is specific for your OS. If you had a previous library installed, it will be uninstalled, and a new one will be installed according to the source code you are using. You can modify this behavior with the following flags:
> ```
This has been changed now. `make PythonAPI` will build both the `egg` and the `wheel`. The wheel is not installed automatically. Also, the `--no-install-wheel` command is not longer available.
___
*[Docs/build_windows.md, line 50 at r3](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfYHSNzCq09xIb25KKh:-MfYHSNzCq09xIb25KKi:b8tpk2k) ([raw file](https://github.com/carla-simulator/carla/blob/1f84becd864ea93cfa6050e61f87b07ceb057b3e/Docs/build_windows.md#L50)):*
> ```
> CARLA requires some Python dependencies to be installed with `pip version >= 20.3`.
> ```
Same comment as in Linux


<!-- Sent from Reviewable.io -->

2021-07-27 09:14 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_linux.md, line 68 at r3](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfYFfaC5MUPKmtMKEFp:-MfbEVolAe6NM_1rZO8k:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/1f84becd864ea93cfa6050e61f87b07ceb057b3e/Docs/build_linux.md#L68)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> CARLA requires some Python dependencies to be installed with `pip version >= 20.3`.
> ```
The dependencies are not required to be installed with pip>=20.3. pip>=20.3 is necessary to install the CARLA PythonAPI with pip. I think it is fine to say here to update pip to 20.3 or greater. But maybe omit the part  `CARLA requires some Python dependencies to be installed with pip version >= 20.3`. Also it would be necessary to update `pip3`
</blockquote></details>

Done.
___
*[Docs/build_linux.md, line 223 at r3](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfYH30d1b10ZdlEUAHn:-MfbEXqd7QXnggzPsJ7P:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/1f84becd864ea93cfa6050e61f87b07ceb057b3e/Docs/build_linux.md#L223)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Every time you run `make PythonAPI` a `.whl` file containing the CARLA client library will be built and installed for your system. This `.whl` cannot be distributed as it is specific for your OS. If you had a previous library installed, it will be uninstalled, and a new one will be installed according to the source code you are using. You can modify this behavior with the following flags:
> ```
This has been changed now. `make PythonAPI` will build both the `egg` and the `wheel`. The wheel is not installed automatically. Also, the `--no-install-wheel` command is not longer available.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 10:23 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 12 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_faq.md, line 414 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbIS501N1Zhjd7Qk5k:-MfbIS501N1Zhjd7Qk5l:b-s5t775) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_faq.md#L414)):*
> ```
> ```sh
> # If you installed the .whl
> # Python 3
> pip3 uninstall <wheel-file-name>.whl
> # Python 2
> pip uninstall <wheel-file-name>.whl
> # If you installed the PyPi package
> # Python 3
> pip3 uninstall carla
> # Python 2
> pip uninstall carla
> ```
> ```
To uninstall the package is always the same:
```
pip/pip3 uninstall carla
```
It doesn't matter if you install it using directly the wheel or with pypi
___
*[Docs/build_linux.md, line 223 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbNdFCCoQxqs5fKPXd:-MfbNdFCCoQxqs5fKPXe:b-s55o2) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_linux.md#L223)):*
> ```
> Python versions 2.7, 3.6, 3.7, and 3.8 are supported
> ```
I wouldn't say that only this python versions are supported. When compiling from source you can compile against any version of python. It is true that we will only distribute the PythonAPI for those python versions but I would omit this information here. 
___
*[Docs/build_linux.md, line 234 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbR9g-3KkHHACqLAtN:-MfbR9g-3KkHHACqLAtO:b-oivlp8) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_linux.md#L234)):*
> ```
> The `.egg` file should be added to your `PYTHONPATH`. All of CARLA's example scripts automatically [look for this file](build_system.md#versions-prior-to-0912) when importing CARLA.
> ```
I would rewrite this sentence. When running the CARLA's example scripts it is not necessary to add anything to the `PYTHONPATH`
___
*[Docs/build_system.md, line 90 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbOrZr-BIRdm6F3ukN:-MfbOrZr-BIRdm6F3ukO:b-5b0csk) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_system.md#L90)):*
> ```
> Python 2.7, 3.6, 3.7, and 3.8 are supported.
> ```
Same as before. When compiling from source you can target other python versions.
___
*[Docs/build_windows.md, line 206 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbP7RwBMmc1We2-yJA:-MfbP7RwBMmc1We2-yJB:bco1a7j) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_windows.md#L206)):*
> ```
> Python versions 2.7, 3.6, 3.7, and 3.8 are supported.
> ```
Same as in Linux
___
*[Docs/build_windows.md, line 217 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbRfdC6OT1KnEbj9VO:-MfbRfdC6OT1KnEbj9VP:bqeq7l5) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_windows.md#L217)):*
> ```
> he `.egg` file will automatically be added to your `PYTHONPATH`. All of CARLA's example scripts automatically [look for this file](build_system.md#versions-prior-to-0912) when importing CARLA.
> ```
Same as in Linux.
___
*[Docs/start_quickstart.md, line 22 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbS6Ie6IW1OzviZS1J:-MfbS6Ie6IW1OzviZS1K:bwmu10g) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L22)):*
> ```
> If running on Linux, the OS must support __glibc >= 2.27__ (Ubuntu 18.04+)
> ```
This is only for the client when installing it from the PyPI index. Not sure if we should add this requirement here.
___
*[Docs/start_quickstart.md, line 43 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbSw18BsitVAtQgeuT:-MfbSw18BsitVAtQgeuU:b-x5omln) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L43)):*
> ```
> CARLA requires some dependencies for the client library. Install the dependencies according to your operating system:
> ```
It is not necessary to install `wheel` or `auditwheel` to install the CARLA PythonAPI via pip. These packages are only needed when building the wheel.
___
*[Docs/start_quickstart.md, line 160 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbTYFp6HBjbepBAm6V:-MfbTYFp6HBjbepBAm6W:bedgtjz) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L160)):*
> ```
> Python versions 2.7, 3.6, 3.7, and 3.8
> ```
I would omit the python versions here. In CARLA packages, we will provide the same python versions as for the egg files.
___
*[Docs/start_quickstart.md, line 271 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbUKMlEIYEQM7ub_Px:-MfbUKMlEIYEQM7ub_Py:bpn3ugq) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L271)):*
> ```
> ```sh
> # If you installed the .whl
> # Python 3
> pip3 uninstall <wheel-file-name>.whl
> # Python 2
> pip uninstall <wheel-file-name>.whl
> # If you installed the PyPi package
> # Python 3
> pip3 uninstall carla
> # Python 2
> pip uninstall carla
> ```
Same as above. You can uninstall the package using `pip/pip3 uninstall carla`. It doesn't matter if you used the wheel or PyPI index to install it.
___
*[Docs/tuto_G_retrieve_data.md, line 844 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbU2rc6umhyPAb75Mo:-MfbU2rc6umhyPAb75Mp:baqe36a) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/tuto_G_retrieve_data.md#L844)):*
> ```
>  Commented import areas only required if running versions of CARLA prior to 0.9.12
> ```
 I think we can leave this as before as the egg will be available for 0.9.12+


<!-- Sent from Reviewable.io -->

2021-07-27 14:30 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 12 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_faq.md, line 414 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbIS501N1Zhjd7Qk5k:-MfcLq2c2AkZ7jZ55jKT:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_faq.md#L414)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ```sh
> # If you installed the .whl
> # Python 3
> pip3 uninstall <wheel-file-name>.whl
> # Python 2
> pip uninstall <wheel-file-name>.whl
> # If you installed the PyPi package
> # Python 3
> pip3 uninstall carla
> # Python 2
> pip uninstall carla
> ```
> ```
To uninstall the package is always the same:
```
pip/pip3 uninstall carla
```
It doesn't matter if you install it using directly the wheel or with pypi
</blockquote></details>

Done.
___
*[Docs/build_linux.md, line 223 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbNdFCCoQxqs5fKPXd:-MfcLs1yBkinRG1QNQpP:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_linux.md#L223)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Python versions 2.7, 3.6, 3.7, and 3.8 are supported
> ```
I wouldn't say that only this python versions are supported. When compiling from source you can compile against any version of python. It is true that we will only distribute the PythonAPI for those python versions but I would omit this information here. 
</blockquote></details>

Done.
___
*[Docs/build_linux.md, line 234 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbR9g-3KkHHACqLAtN:-MfcLsuY9_vdY4ltag9j:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_linux.md#L234)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> The `.egg` file should be added to your `PYTHONPATH`. All of CARLA's example scripts automatically [look for this file](build_system.md#versions-prior-to-0912) when importing CARLA.
> ```
I would rewrite this sentence. When running the CARLA's example scripts it is not necessary to add anything to the `PYTHONPATH`
</blockquote></details>

Done.
___
*[Docs/build_system.md, line 90 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbOrZr-BIRdm6F3ukN:-MfcLvUD3VNQBtnVMrzP:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_system.md#L90)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Python 2.7, 3.6, 3.7, and 3.8 are supported.
> ```
Same as before. When compiling from source you can target other python versions.
</blockquote></details>

Done.
___
*[Docs/build_windows.md, line 206 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbP7RwBMmc1We2-yJA:-MfcMizE62SLLpNMDoSb:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_windows.md#L206)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Python versions 2.7, 3.6, 3.7, and 3.8 are supported.
> ```
Same as in Linux
</blockquote></details>

Done.
___
*[Docs/build_windows.md, line 217 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbRfdC6OT1KnEbj9VO:-MfcMke75Oi81YnjUB2U:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/build_windows.md#L217)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> he `.egg` file will automatically be added to your `PYTHONPATH`. All of CARLA's example scripts automatically [look for this file](build_system.md#versions-prior-to-0912) when importing CARLA.
> ```
Same as in Linux.
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 22 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbS6Ie6IW1OzviZS1J:-MfcMlgEEmV2jL3-tcuP:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L22)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> If running on Linux, the OS must support __glibc >= 2.27__ (Ubuntu 18.04+)
> ```
This is only for the client when installing it from the PyPI index. Not sure if we should add this requirement here.
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 43 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbSw18BsitVAtQgeuT:-MfcMoxi4KbhwDwwF_ya:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L43)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> CARLA requires some dependencies for the client library. Install the dependencies according to your operating system:
> ```
It is not necessary to install `wheel` or `auditwheel` to install the CARLA PythonAPI via pip. These packages are only needed when building the wheel.
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 160 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbTYFp6HBjbepBAm6V:-MfcMqDCEw0ljC5N7sBm:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L160)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Python versions 2.7, 3.6, 3.7, and 3.8
> ```
I would omit the python versions here. In CARLA packages, we will provide the same python versions as for the egg files.
</blockquote></details>

Done.
___
*[Docs/start_quickstart.md, line 271 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbUKMlEIYEQM7ub_Px:-MfcMrRp5xLxMMEJEFKY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/start_quickstart.md#L271)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> ```sh
> # If you installed the .whl
> # Python 3
> pip3 uninstall <wheel-file-name>.whl
> # Python 2
> pip uninstall <wheel-file-name>.whl
> # If you installed the PyPi package
> # Python 3
> pip3 uninstall carla
> # Python 2
> pip uninstall carla
> ```
Same as above. You can uninstall the package using `pip/pip3 uninstall carla`. It doesn't matter if you used the wheel or PyPI index to install it.
</blockquote></details>

Done.
___
*[Docs/tuto_G_retrieve_data.md, line 844 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbU2rc6umhyPAb75Mo:-MfcMsKd5F4xUo_sVv5z:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/tuto_G_retrieve_data.md#L844)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
>  Commented import areas only required if running versions of CARLA prior to 0.9.12
> ```
 I think we can leave this as before as the egg will be available for 0.9.12+
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 14:33 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_faq.md, line 147 at r7](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfhTniw5RdbZfJx73bD:-MfhTnix0ycbfCV4Y9xJ:b-pmekp8) ([raw file](https://github.com/carla-simulator/carla/blob/5ad74a4785db0adfcedc60f93cdeae6efa96663f/Docs/build_faq.md#L147)):*
> ```
> CARLA used `.egg` files for the client library in versions prior to 0.9.12. If you are using 0.9.12+, `.whl` files are used instead and the information in this section will not be relevant to you.
> ```
In 0.9.12+ we also have eggs. I would copy and paste the sentence you have in the Windows section:
```
If you are using 0.9.12+, there are several methods to use/install the client library. If you are using one of the newer methods for the client library (.whl or PyPi download) the information in this section will not be relevant to you.
```
___
*[Docs/build_windows.md, line 211 at r7](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfhVMbG3auP5WdWzIKt:-MfhVMbG3auP5WdWzIKu:bd6hqwc) ([raw file](https://github.com/carla-simulator/carla/blob/5ad74a4785db0adfcedc60f93cdeae6efa96663f/Docs/build_windows.md#L211)):*
> ```
> Optionally, to compile the PythonAPI for a specific version of Python, run the below command in the root CARLA directory.
> ```sh
>     # Delete versions as required
>     make PythonAPI ARGS="--python-version=2.7, 3.6, 3.7, 3.8"
> ```
I just remember this option is not available in Windows. The PythonAPI is built against the default python3 installation. We can just remove this part of the section. 
___
*[Docs/tuto_G_retrieve_data.md, line 844 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbU2rc6umhyPAb75Mo:-MfhWfcgEePtl7Ts2iAc:b-ht2o8t) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/tuto_G_retrieve_data.md#L844)):*
<details><summary><i>Previously, corkyw10 (Corinne) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please, remove also the # in the code.


<!-- Sent from Reviewable.io -->

2021-07-28 15:03 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_faq.md, line 147 at r7](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfhTniw5RdbZfJx73bD:-Mfhbn19CJDF3k_Cssj4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/5ad74a4785db0adfcedc60f93cdeae6efa96663f/Docs/build_faq.md#L147)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> CARLA used `.egg` files for the client library in versions prior to 0.9.12. If you are using 0.9.12+, `.whl` files are used instead and the information in this section will not be relevant to you.
> ```
In 0.9.12+ we also have eggs. I would copy and paste the sentence you have in the Windows section:
```
If you are using 0.9.12+, there are several methods to use/install the client library. If you are using one of the newer methods for the client library (.whl or PyPi download) the information in this section will not be relevant to you.
```
</blockquote></details>

Done.
___
*[Docs/build_windows.md, line 211 at r7](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfhVMbG3auP5WdWzIKt:-MfhcikL3B3KuMD7ElkG:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/5ad74a4785db0adfcedc60f93cdeae6efa96663f/Docs/build_windows.md#L211)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Optionally, to compile the PythonAPI for a specific version of Python, run the below command in the root CARLA directory.
> ```sh
>     # Delete versions as required
>     make PythonAPI ARGS="--python-version=2.7, 3.6, 3.7, 3.8"
> ```
I just remember this option is not available in Windows. The PythonAPI is built against the default python3 installation. We can just remove this part of the section. 
</blockquote></details>

Done.
___
*[Docs/tuto_G_retrieve_data.md, line 844 at r5](https://reviewable.io/reviews/carla-simulator/carla/4325#-MfbU2rc6umhyPAb75Mo:-MfhcSKS9QtKLzCR-TnV:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/aa4d665c6b91e35bd342bb3fe45e8207c38670f6/Docs/tuto_G_retrieve_data.md#L844)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

Please, remove also the # in the code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 08:38 UTC, joel-mb requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_linux.md, line 250 at r9](https://reviewable.io/reviews/carla-simulator/carla/4325#-MflP2JKAr9O6srxId9_:-MflP2JL4pLEnKDXQcxA:b-4f45c6) ([raw file](https://github.com/carla-simulator/carla/blob/05ab126555e0cde544063c7381d46a875a60cd25/Docs/build_linux.md#L250)):*
> ```
> >This `.whl` file cannot be distributed as it is built specifically for your OS. To build a `.whl` for distribution, you can target a different system by using the following flag:
> >- `make PythonAPI --target-wheel-platform="<platform>"` will build and repair the `.whl` file using `auditwheel` for a specific [platform](https://github.com/pypa/manylinux). External shared dependencies will be included in the file. The packaged version of the CARLA `.whl` targets the `manylinux_2_27_x86_64` platform.
> ```
Please, remove this part.
___
*[Docs/build_windows.md, line 50 at r9](https://reviewable.io/reviews/carla-simulator/carla/4325#-MflMnpx3sfZs1yKnot6:-MflMnpx3sfZs1yKnot7:b-atjoap) ([raw file](https://github.com/carla-simulator/carla/blob/05ab126555e0cde544063c7381d46a875a60cd25/Docs/build_windows.md#L50)):*
> ```
> Starting with CARLA 0.9.12, users have the option to install the CARLA Python API using `pip` or `pip3`. Version 20.3 or higher is required. To check if you have a suitable version, run the following command:
> ```sh
> # For Python 3
> pip3 -V
> # For Python 2
> pip -V
> ```
> If you need to upgrade:
> ```sh
> # For Python 3
> pip3 install --upgrade pip
> # For Python 2
> pip install --upgrade pip
> ```
> You must install the following Python dependencies:
> ```sh
> # Python 3
> pip3 install --user setuptools
> pip3 install --user wheel
> # Python 2
> pip install --user setuptools
> pip install --user wheel
> ```
> ```
Please, leave only the part for Python3. For windows we only provide support for Python3, not for Python2.


<!-- Sent from Reviewable.io -->

2021-07-29 09:03 UTC, corkyw10 reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @corkyw10 and @joel-mb)

___
*[Docs/build_linux.md, line 250 at r9](https://reviewable.io/reviews/carla-simulator/carla/4325#-MflP2JKAr9O6srxId9_:-MflVJqg2VGluhJu8Udl:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/05ab126555e0cde544063c7381d46a875a60cd25/Docs/build_linux.md#L250)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> >This `.whl` file cannot be distributed as it is built specifically for your OS. To build a `.whl` for distribution, you can target a different system by using the following flag:
> >- `make PythonAPI --target-wheel-platform="<platform>"` will build and repair the `.whl` file using `auditwheel` for a specific [platform](https://github.com/pypa/manylinux). External shared dependencies will be included in the file. The packaged version of the CARLA `.whl` targets the `manylinux_2_27_x86_64` platform.
> ```
Please, remove this part.
</blockquote></details>

Done.
___
*[Docs/build_windows.md, line 50 at r9](https://reviewable.io/reviews/carla-simulator/carla/4325#-MflMnpx3sfZs1yKnot6:-MflVL3JBil-uo5UT44J:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/05ab126555e0cde544063c7381d46a875a60cd25/Docs/build_windows.md#L50)):*
<details><summary><i>Previously, joel-mb wrote…</i></summary><blockquote>

> ```
> Starting with CARLA 0.9.12, users have the option to install the CARLA Python API using `pip` or `pip3`. Version 20.3 or higher is required. To check if you have a suitable version, run the following command:
> ```sh
> # For Python 3
> pip3 -V
> # For Python 2
> pip -V
> ```
> If you need to upgrade:
> ```sh
> # For Python 3
> pip3 install --upgrade pip
> # For Python 2
> pip install --upgrade pip
> ```
> You must install the following Python dependencies:
> ```sh
> # Python 3
> pip3 install --user setuptools
> pip3 install --user wheel
> # Python 2
> pip install --user setuptools
> pip install --user wheel
> ```
> ```
Please, leave only the part for Python3. For windows we only provide support for Python3, not for Python2.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-29 23:43 UTC, joel-mb approved these changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/4325)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @corkyw10 and @joel-mb)



<!-- Sent from Reviewable.io -->

2021-07-30 07:44 UTC, merged