Native Ackermann Controller
carla-simulator/carla pull request #5148
Opened 2022-02-07 11:59 UTC by joel-mb

#### Description

This PR integrates a native Ackermann Controller in the CARLA server. Ackermann commands can be applied to the vehicle in the following way:

```py
vehicle.apply_ackermann_control(carla.VehicleAckermannControl(speed=10.0))
```

#### Where has this been tested?

  * **Platform(s):** Ubuntu 18.04
  * **Python version(s):** 2.7, 3.6, 3.7, 3.8
  * **Unreal Engine version(s):** 4.26

#### Possible Drawbacks

The default PID works well for most of the vehicles but it may need some tunning if we change the simulation conditions (e.g., async mode, different timestep length, ...)

2022-02-07 16:35 UTC, jackbart94 requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 0 of 24 files reviewed, 15 unresolved discussions (waiting on @glopezdiest and @joel-mb)

___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 41 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvJzAu10jTXI7K3ltYd:-MvJzAu10jTXI7K3ltYe:b4orpfh) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L41)):*
> ```cpp
>         << ", speed=" << std::to_string(control.speed)
>         << ", acceleration=" << std::to_string(control.acceleration)
>         << ", jerk=" << std::to_string(control.jerk) << ')';
> ```

Remove prints



_Code quote:_
```cpp
  std::ostream &operator<<(std::ostream &out, const VehicleAckermannControl &control) {
    out << "VehicleAckermannControl(steer=" << std::to_string(control.steer)
        << ", steer_speed=" << std::to_string(control.steer_speed)
        << ", speed=" << std::to_string(control.speed)
        << ", acceleration=" << std::to_string(control.acceleration)
        << ", jerk=" << std::to_string(control.jerk) << ')';
```
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 120 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-1eW0y84cDixFLI-:-MvK-1eXDUWgJ0xdn_Kn:b4orpfh) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L120)):*
> ```cpp
> 
>   std::ostream &operator<<(std::ostream &out, const AckermannControllerSettings &settings) {
>     out << "AckermannControllerSettings(speed_kp=" << std::to_string(settings.speed_kp)
> ```

Remove prints



_Code quote:_
```cpp
  std::ostream &operator<<(std::ostream &out, const AckermannControllerSettings &settings) {
    out << "AckermannControllerSettings(speed_kp=" << std::to_string(settings.speed_kp)
        << ", speed_ki=" << std::to_string(settings.speed_ki)
        << ", speed_kd=" << std::to_string(settings.speed_kd)
        << ", accel_kp=" << std::to_string(settings.accel_kp)
        << ", accel_ki=" << std::to_string(settings.accel_ki)
        << ", accel_kd=" << std::to_string(settings.accel_kd)  << ')';
```
___
*[PythonAPI/examples/manual_control.py, line 279 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-5oGExMLUfj22pMH:-MvK-5oGExMLUfj22pMI:br4e6pn) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L279)):*
> ```Python
>             spawn_points = self.map.get_spawn_points()
>             spawn_point = random.choice(spawn_points) if spawn_points else carla.Transform()
>             spawn_point = carla.Transform(
> ```

Remove forced spawn point



_Code quote:_
```Python
            spawn_point = carla.Transform(
                carla.Location(x=-250.0, y=245.0, z=2.0),
                carla.Rotation()
            )
```
___
*[PythonAPI/examples/manual_control.py, line 514 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-9-bBfWJlVHhn-BC:-MvK-9-bBfWJlVHhn-BD:b-hf83gm) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L514)):*
> ```Python
>                         world.player.apply_ackermann_controller_settings(
>                             carla.AckermannControllerSettings(
>                                speed_kp=0.15, speed_ki=0.0, speed_kd=0.25,
> ```

a small comment here so that users know they can change them



_Code quote:_
```Python
                            carla.AckermannControllerSettings(
                               speed_kp=0.15, speed_ki=0.0, speed_kd=0.25,
                               accel_kp=0.01, accel_ki=0.0, accel_kd=0.01
                            )
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorData.cpp, line 105 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-M374W2SBr_20z04:-MvK-M3818KENGXMPwe-:byc9qgk) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorData.cpp#L105)):*
> ```cpp
>     PhysicsControl = Vehicle->GetVehiclePhysicsControl();
>   }
>   // TODO(joel): Record the state of the ackermann control
> ```

is this TODO done?
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp, line 882 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-V8f-MRkRLXarlD0:-MvK-V8f-MRkRLXarlD1:bcmwg22) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp#L882)):*
> ```cpp
>   if (IsDormant())
>   {
>     //FVehicleData* ActorData = GetActorData<FVehicleData>();
> ```

Why is this commented?



_Code quote:_
```cpp
    //FVehicleData* ActorData = GetActorData<FVehicleData>();
    //PhysicsControl = ActorData->PhysicsControl;
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp, line 902 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-XvlDkiSD2qPnyeh:-MvK-XvlDkiSD2qPnyei:bkxzpsf) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp#L902)):*
> ```cpp
>   if (IsDormant())
>   {
>     // FVehicleData* ActorData = GetActorData<FVehicleData>();
> ```

Same as above, why is it commented



_Code quote:_
```cpp
    // FVehicleData* ActorData = GetActorData<FVehicleData>();
    // ActorData->PhysicsControl = PhysicsControl;
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 38 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-m8K5cfVhGBJgfC-:-MvK-m8K5cfVhGBJgfC0:blalkn4) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L38)):*
> ```cpp
>   SpeedController.Ki = Settings.SpeedKi;
>   SpeedController.Kd = Settings.SpeedKd;
>   
> ```

Tab here
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 122 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK05FF686IUWw29c-n:-MvK05FF686IUWw29c-o:b-1kbq6b) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L122)):*
> ```cpp
>       AccelControlPedalTarget
>       //BrakeUpperBorder,
>       //ThrottleLowerBorder
> ```

A bit of commented stuff over here, do we have to change a few things?



_Code quote:_
```cpp

      //VehiclePitch,
      Control.Steer,
      Control.Throttle,
      Control.Brake,
      Control.Gear,
      //SpeedController.Proportional,
      //SpeedController.Integral,
      //SpeedController.Derivative,
      SpeedControlAccelDelta,
      SpeedControlAccelTarget,
      //AccelerationController.Proportional,
      //AccelerationController.Integral,
      //AccelerationController.Derivative,
      AccelControlPedalDelta,
      AccelControlPedalTarget
      //BrakeUpperBorder,
      //ThrottleLowerBorder
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 220 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK0Zc4BXEjqaVWCWhc:-MvK0Zc4BXEjqaVWCWhd:b2nicts) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L220)):*
> ```cpp
>   LastVehicleSpeed = VehicleSpeed;
>   LastVehicleAcceleration = VehicleAcceleration;
>   
> ```

tab
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 231 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK0f-YASeI6Lw5Azud:-MvK0f-YASeI6Lw5Azue:bl2di48) ( [...]

2022-02-07 16:55 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 0 of 24 files reviewed, 19 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 41 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvJzAu10jTXI7K3ltYd:-MvK2JblAeoMrIrOpJXt:bhgalsu) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L41)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Remove prints
</blockquote></details>

These are not debugging prints. These prints are necessary to do a print from the PythonAPI.
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 120 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-1eW0y84cDixFLI-:-MvK2svCANqzTIw94KDK:brhumzt) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L120)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Remove prints
</blockquote></details>

Same here.
___
*[PythonAPI/examples/manual_control.py, line 279 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-5oGExMLUfj22pMH:-MvK3r-u3KHvczjtnpb9:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L279)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Remove forced spawn point
</blockquote></details>

Done.
___
*[PythonAPI/examples/manual_control.py, line 514 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-9-bBfWJlVHhn-BC:-MvK3tYe5up53875L81Y:b-2k4w6i) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L514)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

a small comment here so that users know they can change them
</blockquote></details>

I've removed this. These parameters are the default ones. In the manual control users won't be able to modify this. 
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 38 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-m8K5cfVhGBJgfC-:-MvK4hZ42wWEFPQR3XNK:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L38)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Tab here
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 220 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK0Zc4BXEjqaVWCWhc:-MvK4orf1iXKYBSDGGTE:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L220)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 227 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK4Fz6E3lvwagjPixT:-MvK5gMJ5cboxZn58ljz:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L227)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

comment here why this formula is applied
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 231 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK0f-YASeI6Lw5Azud:-MvK5cxdCBIz7oW69O5E:b-br1sah) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L231)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Could you introduce an option to include N-wheeled vehicles as well?
</blockquote></details>

Removed. I was not necessary.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h, line 1 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK3x85-fX-lqrE9aFi:-MvK5j3vBLfGWSrTZaEN:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h#L1)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h, line 54 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK1-DJ6wG8mD4bMcaK:-MvK5sUHBBD6q0jK_rIh:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h#L54)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tabs
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h, line 139 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK1CgM9-m2rS4w8vdz:-MvK5zFFB-o7psreN8ck:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h#L139)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h, line 154 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK3qzKBz9sV0JioRr4:-MvK6-HK3A_XGpYAnv6P:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AckermannController.h#L154)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

it's more or less in all files, but here it misses a newline
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 17:01 UTC, jackbart94 requested changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 0 of 24 files reviewed, 23 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 345 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK62Az39ixlPZR8TqF:-MvK62Az39ixlPZR8TqG:b-uv728e) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L345)):*
> ```cpp
>       arg("speed") = 0.0f,
>       arg("acceleration") = 0.0f,
>       arg("jerk") = 0.0f)))
> ```

these are already initialized in the .h. Is this necessary? or maybe the other one can be removed. Either way, just asking



_Code quote:_
```cpp
      (arg("steer") = 0.0f,
      arg("steer_speed") = 0.0f,
      arg("speed") = 0.0f,
      arg("acceleration") = 0.0f,
      arg("jerk") = 0.0f)))
```
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 358 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK5sA26pVJNnJvT3a5:-MvK5sA35gu-Shi-icQz:b-uv728e) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L358)):*
> ```cpp
>   class_<cr::AckermannControllerSettings>("AckermannControllerSettings")
>     .def(init<float, float, float, float, float, float>(
>       (arg("speed_kp") = 0.0f,
> ```

these are already initialized in the .h. Is this necessary? or maybe the other one can be removed. Either way, just asking



_Code quote:_
```cpp
      (arg("speed_kp") = 0.0f,
      arg("speed_ki") = 0.0f,
      arg("speed_kd") = 0.0f,
      arg("accel_kp") = 0.0f,
      arg("accel_ki") = 0.0f,
      arg("accel_kd") = 0.0f)))
```
___
*[PythonAPI/examples/manual_control.py, line 643 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK6Uct7Mab4-k2D5KX:-MvK6Uct7Mab4-k2D5KY:b-rse12o) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L643)):*
> ```Python
>             self._control.hand_brake = keys[K_SPACE]
>         else:
>             self._ackermann_control.steer = round(self._steer_cache, 1)
> ```

It's better to have if self._ackermann_enabled and those cases, and placing the else as the standard one for readability



_Code quote:_
```Python
        if not self._ackermann_enabled:
            self._control.steer = round(self._steer_cache, 1)
            self._control.hand_brake = keys[K_SPACE]
        else:
            self._ackermann_control.steer = round(self._steer_cache, 1)
```
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 140 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK7DmlAPT_MLFEyA6H:-MvK7DmlAPT_MLFEyA6I:b2nicts) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L140)):*
> ```cpp
>     return true;
>   }
>   return false;  
> ```

tab


<!-- Sent from Reviewable.io -->

2022-02-07 17:04 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 0 of 24 files reviewed, 23 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 122 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK05FF686IUWw29c-n:-MvK7DKFCZ0klO6xcxEB:ba3dfob) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L122)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

A bit of commented stuff over here, do we have to change a few things?
</blockquote></details>

Removed
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp, line 140 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK7DmlAPT_MLFEyA6H:-MvK7uORDS93Ph2XXSfY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/AcekrmannController.cpp#L140)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 101 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK1LPk9IWjQ5oxvnV4:-MvK8-Io-T3xkVEIPY2Q:ba3dfob) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L101)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

A print that can be removed
</blockquote></details>

Removed
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp, line 731 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK1NYE1dJPtabpEX_h:-MvK89eO1JlVEa22-CMp:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Vehicle/CarlaWheeledVehicle.cpp#L731)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 17:13 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 0 of 24 files reviewed, 23 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 345 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK62Az39ixlPZR8TqF:-MvK9eIJ1pIIMfrbbw09:bo3apg4) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L345)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

these are already initialized in the .h. Is this necessary? or maybe the other one can be removed. Either way, just asking
</blockquote></details>

This initialization is necessary for the PythonAPI
___
*[PythonAPI/carla/source/libcarla/Control.cpp, line 358 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK5sA26pVJNnJvT3a5:-MvK9mYZA7S-egeGHzF6:brhumzt) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/carla/source/libcarla/Control.cpp#L358)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

these are already initialized in the .h. Is this necessary? or maybe the other one can be removed. Either way, just asking
</blockquote></details>

Same here.


<!-- Sent from Reviewable.io -->

2022-02-08 09:35 UTC, glopezdiest reviewed
The PR comment seems to be wrong about the `apply_ackermann_controller_settings. Does it miss a carla.AckermannControllerSettings? Also, acceleration = 0 means that the acceleration is unbounded?

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148#-:-MvNfnOJDoL_GQA3NmXk:bf6ji34)* status: 16 of 24 files reviewed, 27 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)



<!-- Sent from Reviewable.io -->

2022-02-08 09:57 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 16 of 27 files reviewed, 27 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorData.cpp, line 105 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-M374W2SBr_20z04:-MvNl5HT9HLbK0P6FD3T:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorData.cpp#L105)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

is this TODO done?
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp, line 882 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-V8f-MRkRLXarlD0:-MvNl6MC5b3TXEdEocGU:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp#L882)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Why is this commented?
</blockquote></details>

Done.
___
*[Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp, line 902 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK-XvlDkiSD2qPnyeh:-MvNl7Fg1z65_m-ZQRFZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/CarlaActor.cpp#L902)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

Same as above, why is it commented
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 10:01 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 16 of 27 files reviewed, 27 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[LibCarla/source/carla/rpc/VehicleAckermannControl.h, line 24 at r6](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvNdL-mB2NTBOS8Tet0:-MvNlhQYEEr1__PRAFvD:b-9ngtw5) ([raw file](https://github.com/carla-simulator/carla/blob/cc5d22d0e175d708ea722ce049bcd5fbc14ee254/LibCarla/source/carla/rpc/VehicleAckermannControl.h#L24)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Why "in_steer" and not "steer". It feels liek a weird name to me
</blockquote></details>

I've used the `in_xxx` variable names to maintain the same notation as in the `VehicleControl` structure.


<!-- Sent from Reviewable.io -->

2022-02-08 12:28 UTC, joel-mb reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: 11 of 27 files reviewed, 27 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)

___
*[CHANGELOG.md, line 3 at r6](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvNb10v2E1YX9XmCAhS:-MvOERys2CecFv-3dMxE:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/cc5d22d0e175d708ea722ce049bcd5fbc14ee254/CHANGELOG.md#L3)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Add more information along the lines of "New API function X and Y to (de)activate the Ackermann controller of a vehicle
</blockquote></details>

Done.
___
*[LibCarla/source/carla/client/Vehicle.h, line 58 at r6](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvNbbQbDy4MJMgOUdzU:-MvOBIE932yt6pIO-6aI:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/cc5d22d0e175d708ea722ce049bcd5fbc14ee254/LibCarla/source/carla/client/Vehicle.h#L58)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Comments are missing here
</blockquote></details>

Done.
___
*[LibCarla/source/carla/rpc/VehicleAckermannControl.h, line 53 at r6](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvNdF-P8D8VZyBX1xIP:-MvOA9J98xG1UVrvsFkn:boy1tis) ([raw file](https://github.com/carla-simulator/carla/blob/cc5d22d0e175d708ea722ce049bcd5fbc14ee254/LibCarla/source/carla/rpc/VehicleAckermannControl.h#L53)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This steer speed is not exposed in the Python API? Is it currently not used?
</blockquote></details>

We are currently using it.
___
*[PythonAPI/examples/manual_control.py, line 747 at r2](https://reviewable.io/reviews/carla-simulator/carla/5148#-MvK2cUgAuDQrtIIMOkf:-MvOAiiA69FoyiFYliqI:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b3d7697de1da1315ecbadd2b184b42ecd0ac5dcd/PythonAPI/examples/manual_control.py#L747)):*
<details><summary><i>Previously, jackbart94 (Jacopo Bartiromo) wrote…</i></summary><blockquote>

You can remove this if it's not updated during the simulation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 12:42 UTC, joel-mb reviewed
Updated PR description with your comments.

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148#-:-MvOLar7CHiKLqDWgKQn:b-3k6629)* status: 11 of 27 files reviewed, 27 unresolved discussions (waiting on @glopezdiest, @jackbart94, and @joel-mb)



<!-- Sent from Reviewable.io -->

2022-02-08 13:20 UTC, glopezdiest submitted a review, later dismissed
> Reviewed 3 of 23 files at r1, 1 of 2 files at r6, 2 of 3 files at r7, 3 of 3 files at r8, 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: all files reviewed, 23 unresolved discussions (waiting on @jackbart94 and @joel-mb)



<!-- Sent from Reviewable.io -->

2022-02-08 16:23 UTC, glopezdiest approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @joel-mb)



<!-- Sent from Reviewable.io -->

2022-02-08 19:15 UTC, merged