Marcel/gbuffer dev merge
carla-simulator/carla pull request #5960
Opened 2022-11-21 16:00 UTC by MarcelPiNacy

#### Description

This PR introduces the ability to extract most of the GBuffer textures from a sensor. From the Python API, this can be done using the `listen_to_gbuffer` sensor method.

#### Where has this been tested?

  * **Platform(s):** Windows 10, Ubuntu 20
  * **Python version(s):** 3.8
  * **Unreal Engine version(s):** Carla (marcel/gbuffer_view)

2022-11-22 09:12 UTC, Axel1092 requested changes
> Reviewed 7 of 26 files at r2, 18 of 33 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 26 of 41 files reviewed, 20 unresolved discussions (waiting on @MarcelPiNacy)

___
*[`LibCarla/source/carla/client/detail/Simulator.cpp` line 384 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTZhQ7ECpjlV8RCbjJ:-NHTZhQ7ECpjlV8RCbjK:b-gegmgi) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/LibCarla/source/carla/client/detail/Simulator.cpp#L384)):*
> ```cpp
>   void Simulator::UnSubscribeFromSensor(Actor &sensor) {
>     _client.UnSubscribeFromStream(sensor.GetActorDescription().GetStreamToken());
> #if 0
> ```

Remove unnecessary code
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 77 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_CwK9cCRJaN-NYsw:-NHT_CwK9cCRJaN-NYsx:b-5fcnmf) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L77)):*
> ```Python
>     # In this tutorial script, we are going to add a vehicle to the simulation
>     # and let it drive in autopilot. We will also create a camera attached to
>     # that vehicle, and save all the images generated by the camera to disk.
> ```

Add a better description regarding the gbuffers here, so that it is clearer
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 126 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_LPHAe_um7HuA4jZ:-NHT_LPI1AshugPtbD0G:b-u7mb4d) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L126)):*
> ```Python
>         height = 1080
> 
>         # Let's add now a "depth" camera attached to the vehicle. Note that the
> ```

not a depth camera
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 138 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_PZI-CgDq8hLPnvb:-NHT_PZJ46Sa_msYSplR:b-40lgcz) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L138)):*
> ```Python
>         # Regular image capture, this is currently mandatory for the GBuffers to be extracted:
>         camera.listen(SaveFinalColorTexture)
>         # GBuffer image capture:
> ```

explain a bit more elaborated here, this is a tutorial
___
*[`Unreal/CarlaUE4/Config/OptionalModules.ini` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_X0XACJH0UZIUtFw:-NHT_X0XACJH0UZIUtFx:btfb1qm) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Config/OptionalModules.ini#L1)):*
> ```INI
> "CarSim OFF" "Chrono OFF" 
> ```

You should not commit this file, please remove it
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTagLP1S7ZXB5cIl-a:-NHTagLP1S7ZXB5cIl-b:b26wc3p) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h#L1)):*
> ```objc
> #pragma once
> ```

Missing copyright text
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h` line 27 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_bD4EBpXTStwzXda:-NHT_bD4EBpXTStwzXdb:b2q1izg) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h#L27)):*
> ```objc
>         FReadSurfaceDataFlags Flags,
>         TArrayView<FLinearColor> Out);
> }
> ```

Missing final line break
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTad2O8mR_3RjclWBV:-NHTad2O8mR_3RjclWBW:b26wc3p) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L1)):*
> ```cpp
> #include "Carla/Sensor/ImageUtil.h"
> ```

Missing copyright text
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 140 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_h3vABf3b2vHL_vy:-NHT_h3w1Q34cLYfdiGQ:b-vb2l3z) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L140)):*
> ```cpp
> 		}
> 	}
> }
> ```

Missing line break, also tabs in the entire file, should be spaces
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp` line 69 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_rHp12F0j7b4eof7:-NHT_rHp12F0j7b4eof8:bjyz9g8) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp#L69)):*
> ```cpp
> {
>     SendGBufferTexturesInternal(*this, GBuffer);
> }
> ```

line break
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 11 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_yES3ym6frLAdd6j:-NHT_yES3ym6frLAdd6k:b-n6xmd1) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L11)):*
> ```cpp
> #include "Carla/Game/CarlaStatics.h"
> 
> /*
> ```

Remove commented code if not needed
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 464 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTa3V13os3c0vCawVc:-NHTa3V13os3c0vCawVd:b-2xwtvf) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L464)):*
> ```cpp
>   TRACE_CPUPROFILER_EVENT_SCOPE(ASceneCaptureSensor::EnqueueRenderSceneImmediate);
>   // Creates an snapshot of the scene, requieres bCaptureEveryFrame = false.
> #if 0
> ```

remove non executing code
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.h` line 26 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaFYf59W9sggrIZEi:-NHTaFYf59W9sggrIZEj:bjyz9g8) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.h#L26)):*
> ```objc
> 
> 	virtual const AActor* GetViewOwner() const override;
> };
> ```

line break
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaZ-d7rkBtSTy3eKW:-NHTaZ-d7rkBtSTy3eKX:b26wc3p) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp#L1)):*
> ```cpp
> #include "SceneCaptureComponent2D_CARLA.h"
> ```

Missing copyright text
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp` line 13 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaHFT-Gywky27x7q1:-NHTaHFT-Gywky27x7q2:bjyz9g8) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp#L13)):*
> ```cpp
> {
>     return ViewActor;
> }
> ```

line break
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent_CARLA.h` line 26 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaIl49IP8MMkzTBKY:-NHTa [...]

2022-11-22 15:01 UTC, MarcelPiNacy reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 24 of 43 files reviewed, 20 unresolved discussions (waiting on @Axel1092 and @MarcelPiNacy)

___
*[`LibCarla/source/carla/client/detail/Simulator.cpp` line 384 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTZhQ7ECpjlV8RCbjJ:-NHUNZlEBpxRYc2Yep4K:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/LibCarla/source/carla/client/detail/Simulator.cpp#L384)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Remove unnecessary code
</blockquote></details>

Done.
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 77 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_CwK9cCRJaN-NYsw:-NHUnizKCfZapet3kY0C:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L77)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Add a better description regarding the gbuffers here, so that it is clearer
</blockquote></details>

Done.
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 126 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_LPHAe_um7HuA4jZ:-NHUiUKbBpv2e0cjaCJI:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L126)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

not a depth camera
</blockquote></details>

Done.
___
*[`PythonAPI/examples/tutorial_gbuffer.py` line 138 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_PZI-CgDq8hLPnvb:-NHUiWRWErita5Mzo9D6:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/PythonAPI/examples/tutorial_gbuffer.py#L138)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

explain a bit more elaborated here, this is a tutorial
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTagLP1S7ZXB5cIl-a:-NHUO9z21EOL1QtcwHYB:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h#L1)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Missing copyright text
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h` line 27 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_bD4EBpXTStwzXda:-NHUnkJd0JuIzs5fqhV7:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.h#L27)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Missing final line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTad2O8mR_3RjclWBV:-NHUOH856yVeYDHwjsn8:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L1)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Missing copyright text
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 140 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_h3vABf3b2vHL_vy:-NHUq1Kp8EQQuoSuYzwY:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L140)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Missing line break, also tabs in the entire file, should be spaces
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp` line 69 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_rHp12F0j7b4eof7:-NHUnn5M1B04KKojoeek:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureCamera.cpp#L69)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 11 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_yES3ym6frLAdd6j:-NHUiuqS7KQibJoZiNwP:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L11)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Remove commented code if not needed
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 464 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTa3V13os3c0vCawVc:-NHUiwIs7kcx1M2oUr8G:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L464)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

remove non executing code
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.h` line 26 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaFYf59W9sggrIZEi:-NHUno931GdzVMOhpB7f:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.h#L26)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp` line 1 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaZ-d7rkBtSTy3eKW:-NHUiy2l5ohNyiKJhGuZ:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp#L1)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Missing copyright text
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp` line 13 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaHFT-Gywky27x7q1:-NHUnozGCcsfKixNtCG4:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent2D_CARLA.cpp#L13)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent_CARLA.h` line 26 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHTaIl49IP8MMkzTBKY:-NHUmryZC6NAkD2aHSsw:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent_CARLA.h#L26)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/UE4_Overridden/SceneCaptureComponent_CARLA.cpp` line 1 at r4](https://review [...]

2022-11-22 15:45 UTC, Axel1092 requested changes
> Reviewed 2 of 33 files at r3, 11 of 15 files at r5, 1 of 1 files at r6, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 40 of 43 files reviewed, 4 unresolved discussions (waiting on @MarcelPiNacy)

___
*[`Unreal/CarlaUE4/Config/.gitignore` line 1 at r7](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHUzno29tozGv7ugqOi:-NHUzno29tozGv7ugqOj:bjyz9g8) ([raw file](https://github.com/carla-simulator/carla/blob/b1a9ef1ffac70382af92e0b2acc04af4d87d6b1f/Unreal/CarlaUE4/Config/.gitignore#L1)):*
> ```ignore
> OptionalModules.ini
> ```

line break
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 140 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_h3vABf3b2vHL_vy:-NHUzw3wB9iAcZnNnBEb:b-xi7vo7) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L140)):*
<details><summary><i>Previously, MarcelPiNacy (Marcel Pi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still there are tabs in the file
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 11 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_yES3ym6frLAdd6j:-NHV-Vil5tkY6QDjcUW_:b9vybna) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L11)):*
<details><summary><i>Previously, MarcelPiNacy (Marcel Pi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, the code remains commented here. Be careful, I think these includes are needed.


<!-- Sent from Reviewable.io -->

2022-11-22 16:42 UTC, MarcelPiNacy reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 33 of 45 files reviewed, 4 unresolved discussions (waiting on @Axel1092 and @MarcelPiNacy)

___
*[`Unreal/CarlaUE4/Config/.gitignore` line 1 at r7](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHUzno29tozGv7ugqOi:-NHVD-q34AvVOWg5a9kE:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/b1a9ef1ffac70382af92e0b2acc04af4d87d6b1f/Unreal/CarlaUE4/Config/.gitignore#L1)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

line break
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp` line 140 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_h3vABf3b2vHL_vy:-NHVC5W34o6apA0i1Zt-:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/ImageUtil.cpp#L140)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Still there are tabs in the file
</blockquote></details>

Done.
___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 11 at r4](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHT_yES3ym6frLAdd6j:-NHVCDP1BFWimlZAps9d:bgpkp0w) ([raw file](https://github.com/carla-simulator/carla/blob/4de39a4a562893b117389808b5af0b262a8ce8cc/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L11)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

Not done, the code remains commented here. Be careful, I think these includes are needed.
</blockquote></details>

Oh sorry! I think this was from the dev->gbuffer merge or even earlier. I have removed these commented includes.


<!-- Sent from Reviewable.io -->

2022-11-23 14:27 UTC, Axel1092 requested changes
> Reviewed 1 of 33 files at r3, 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 44 of 45 files reviewed, 1 unresolved discussion (waiting on @MarcelPiNacy)

___
*[`Unreal/CarlaUE4/CarlaUE4.uproject` line 3 at r8](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHZsEJr4D70T7yn6qQ7:-NHZsEJr4D70T7yn6qQ8:bl41skg) ([raw file](https://github.com/carla-simulator/carla/blob/c6efb2e0fe120d06317a2bdf2bca8a57c262a145/Unreal/CarlaUE4/CarlaUE4.uproject#L3)):*
> ```
> {
> 	"FileVersion": 3,
> 	"EngineAssociation": "{F4AD64A5-4015-04BC-E712-009FA5C36CCE}",
> ```

This file should not be commited


<!-- Sent from Reviewable.io -->

2022-11-28 09:06 UTC, Axel1092 approved these changes
> Reviewed 1 of 2 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: all files reviewed, 1 unresolved discussion (waiting on @MarcelPiNacy)



<!-- Sent from Reviewable.io -->

2022-11-28 09:06 UTC, Axel1092 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcelPiNacy)



<!-- Sent from Reviewable.io -->

2022-11-28 11:03 UTC, Axel1092 requested changes
You should add a stop 

> Reviewed 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960#-:-NHxtWsj6-ISu5PXdGOB:b-kqp01z)* status: all files reviewed, 3 unresolved discussions (waiting on @MarcelPiNacy)

___
*[`LibCarla/source/carla/client/ServerSideSensor.cpp` line 64 at r12](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHxsCgH48weZuMvzKUw:-NHxsCgH48weZuMvzKUx:b-fu10qj) ([raw file](https://github.com/carla-simulator/carla/blob/54bd0ca0c49efd101a0774b23994b241ed797a6b/LibCarla/source/carla/client/ServerSideSensor.cpp#L64)):*
> ```cpp
>     GetEpisode().Lock()->UnSubscribeFromGBuffer(*this, GBufferId);
>     listening_mask.reset(GBufferId);
>     if (listening_mask.count() == 1)
> ```

Put braces, even if it is one line statement
___
*[`LibCarla/source/carla/client/ServerSideSensor.cpp` line 71 at r12](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHxsJHSDdDBw_JXuS8_:-NHxsJHSDdDBw_JXuS8a:b-fu10qj) ([raw file](https://github.com/carla-simulator/carla/blob/54bd0ca0c49efd101a0774b23994b241ed797a6b/LibCarla/source/carla/client/ServerSideSensor.cpp#L71)):*
> ```cpp
>     log_debug("calling sensor Destroy() ", GetDisplayId());
>     if (IsListening()) {
>       for (uint32_t i = 1; i != 16; ++i)
> ```

Put braces, even if it is one line statement
___
*[`PythonAPI/carla/source/libcarla/Sensor.cpp` line 45 at r12](https://reviewable.io/reviews/carla-simulator/carla/5960#-NHxss5b8UplL63PjQST:-NHxss5b8UplL63PjQSU:bt60p6s) ([raw file](https://github.com/carla-simulator/carla/blob/54bd0ca0c49efd101a0774b23994b241ed797a6b/PythonAPI/carla/source/libcarla/Sensor.cpp#L45)):*
> ```cpp
>       ("ServerSideSensor", no_init)
>     .def("listen_to_gbuffer", &SubscribeToGBuffer, (arg("gbuffer_id"), arg("callback")))
>     .def("stop_gbuffer", &UnSubscribeFromGBuffer, (arg("gbuffer_id")))
> ```

No need to have intermediate funcion here, use `&cc::ServerSideSensor::StopGBuffer` directly


<!-- Sent from Reviewable.io -->

2022-11-29 09:50 UTC, Axel1092 requested changes
> Reviewed 1 of 2 files at r13, 7 of 7 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: all files reviewed, 1 unresolved discussion (waiting on @MarcelPiNacy)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 477 at r15](https://reviewable.io/reviews/carla-simulator/carla/5960#-NI1lwnv43vFuNk2Sq9k:-NI1lwnv43vFuNk2Sq9l:bqwmql) ([raw file](https://github.com/carla-simulator/carla/blob/0004496a41df00f17fc67cfc41cc0e9b6dc29532/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L477)):*
> ```cpp
>   if (!GBufferStream.Stream.AreClientsListening())
>   {
>     UE_LOG(LogCarla, Verbose, TEXT("Deactivating gbuffer stream for the texture \"%s\"."), GBufferNames[(int)ID]);
> ```

This message will output every frame, better to remove it


<!-- Sent from Reviewable.io -->

2022-11-29 10:02 UTC, MarcelPiNacy reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: 46 of 47 files reviewed, 1 unresolved discussion (waiting on @Axel1092)

___
*[`Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp` line 477 at r15](https://reviewable.io/reviews/carla-simulator/carla/5960#-NI1lwnv43vFuNk2Sq9k:-NI1palL0l05I8OxWUu5:b-896fix) ([raw file](https://github.com/carla-simulator/carla/blob/0004496a41df00f17fc67cfc41cc0e9b6dc29532/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/SceneCaptureSensor.cpp#L477)):*
<details><summary><i>Previously, Axel1092 wrote…</i></summary><blockquote>

This message will output every frame, better to remove it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-29 10:09 UTC, Axel1092 approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/carla/5960)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MarcelPiNacy)



<!-- Sent from Reviewable.io -->

2022-11-29 10:24 UTC, merged