Add a `*.pyi` file for auto-completion & hints.
carla-simulator/carla pull request #7009
Opened 2023-12-16 08:23 UTC by Minokori

#### Description

To enable auto-completion and hints in code editors such as VScode, create a `*.pyi` file. This feature is compatible with `python 3.9` and later versions.

#### Where has this been tested?

  * **Platform(s): Windows Desktop** ...
  * **Python version(s): 3.9.10** ...
  * **Unreal Engine version(s):** ...

#### Possible Drawbacks

It might be incompatible with `python 3.8` or earlier versions.

2024-02-10 16:21 UTC, Daraan commented
So far it works with Python 3.7 without greater issues, but only looked into some small aspects. (Thanks a lot btw.!)

2024-02-11 12:29 UTC, Daraan requested changes

2024-02-13 12:15 UTC, Daraan requested changes

2024-02-13 12:15 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def get_blueprint_library(self) -> list[BlueprintLibrary]:
This returns just a BlueprintLibrary and not a list.
Wording is a bit ambiguous in in the original documentation.

https://carla.readthedocs.io/en/latest/python_api/#carla.World

2024-02-13 13:56 UTC, Daraan requested changes

2024-02-13 13:56 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def __iter__(self):
Can this one be improved too?

2024-02-13 13:56 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def __iter__(self):
`-> List[Actor]`

2024-02-13 13:56 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def __iter__(self):
`-> List[ActorAttribute]:`

2024-02-19 16:35 UTC, Daraan requested changes
Update included in my latest pull request

2024-02-19 16:35 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def parent() -> ["Actor"]:
`[Type]` is not proper. Should be changed to `Optional["Actor"] `or `Union[None, "Actor"]`

2024-02-29 10:00 UTC, Daraan commented
Completed the last todos, and added further fixes as well as a changelog to my pull request on @Minokori's branch.

In my opinion afterwards its ready to merge

2024-03-13 09:31 UTC, Daraan commented
Todo: FutureActor currently undocumented class; see #7236

2024-03-19 14:12 UTC, Daraan requested changes

2024-03-19 14:12 UTC, Daraan commented on PythonAPI/carla/source/carla/libcarla.pyi
> +    def __init__(self, name: str, xodr_content: str) -> list[Transform]:
`__init__` should not return, and this is additionally wrong imo.

Fixes for all `__init__`s included in the latest pushes to my PR

2024-04-17 12:06 UTC, Blyron commented
Hey @Minokori All PRs must be against dev, could you correct this please?

2024-05-07 07:05 UTC, Blyron commented
If this PR does not go against dev we will need to close it and reject it

2024-06-14 17:18 UTC, Daraan commented
I've now opened a rebased and merged PR combining @Minokori and my version. Of course we should prefer Minokori's PR but as it has been kind of stale I now decided to open an up-to-date alternative with #7787 as long as this PR here is not maintained further. I hope this is fine with you all.

2024-09-12 06:33 UTC, closed without merging