Fixing distro deprecation in setup.py
carla-simulator/carla pull request #7257
Opened 2024-03-15 14:10 UTC by azzamh15

fixed distro depreciated features and made not implemented error clear

2024-03-15 15:07 UTC, xavisolesoft requested changes

2024-03-15 15:07 UTC, xavisolesoft commented on PythonAPI/carla/setup.py
> +        supported = ["ubuntu", "debian", "deepin"]
```suggestion
        supported_dists = ["ubuntu", "debian", "deepin"]
```

This variable have a different name on the `NotImplementedError` Exception message.

2024-03-15 15:31 UTC, azzamh15 reviewed
oh really sorry

2024-03-17 15:29 UTC, Daraan commented
For reference this is duplicate of #6802

2024-03-17 16:09 UTC, azzamh15 commented
> For reference this is duplicate of #6802

yes merging branch was stale

2024-03-18 07:43 UTC, xavisolesoft requested changes
Duplicated

2024-03-18 07:46 UTC, azzamh15 commented
closing this pull request as duplicate of #6802

2024-03-18 07:46 UTC, closed without merging