New Sensor: V2X communication
carla-simulator/carla pull request #7490
Opened 2024-04-23 11:57 UTC by grimmmbo

Hi all,

we developed a new sensor for CARLA that aims to integrate simulation of vehicle-to-vehicle / vehicle-to-everything (V2X) communication. Currently, the supported features are

- Cooperative awareness message (CAM)
- Custom message (string, user-supplied during usage)

The sensor integrates a simple physical channel model, differentiating between line-of-sight and non-line-of-sight conditions based on Unreal's raytracing functionality. Various parameters can be set via Python such as standard deviations for noise on the channel and on the simulated data for CAM.

Documentation in ref_sensors and Python API is updated accordingly. The code builds with 0.9.15 latest dev version on Ubuntu 20.04 with Python 3.10. Original tests with make check are passing.

Design details and considerations will soon be published in a research paper at the IEEE Intelligent Vehicles conference. 
If there are any changes required to integrate that feature to the main branch, please let me know.

2024-04-23 12:12 UTC, Blyron commented
Hello! 
Thanks for your PR. We are gonna make some tests on Ubuntu 22.04. Could you update the CHANGELOG.md as your contribution might be very interesting for some users?

2024-04-23 12:24 UTC, Blyron requested changes

2024-04-23 12:24 UTC, Blyron commented on LibCarla/source/carla/sensor/data/V2XEvent.h
> +} // namespace carla
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on LibCarla/source/carla/sensor/s11n/V2XSerializer.cpp
> +} // namespace carla
EEOF is missing here

2024-04-23 12:24 UTC, Blyron commented on LibCarla/source/carla/sensor/s11n/V2XSerializer.cpp
> +    SharedPtr<SensorData> CustomV2XDataSerializer::Deserialize(RawData &&data) {
Tab is incorrect

2024-04-23 12:24 UTC, Blyron commented on LibCarla/source/carla/sensor/s11n/V2XSerializer.h
> +} // namespace carla
EOF is missing here

2024-04-23 12:24 UTC, Blyron commented on PythonAPI/carla/source/libcarla/V2XData.cpp
> +// boost::python::list GetVehicleExteriorLightList(const ITSContainer::ExteriorLights_t exteriorLights)
Please remove commented code if its not gonna be used

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/CustomV2XSensor.h
> +};
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/CaService.h
> +};
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.h
> +};
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/VehicleObstacle.cpp
> +}
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2XSensor.cpp
> +}
EOF is missing

2024-04-23 12:24 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2XSensor.h
> +};
EOF is missing

2024-04-23 13:19 UTC, Blyron commented on PythonAPI/carla/source/libcarla/V2XData.cpp
> +    // ValueConfidence.clear();
Why this comments still here?

2024-04-23 13:19 UTC, Blyron commented on PythonAPI/carla/source/libcarla/V2XData.cpp
> +        // BVCHighFrequency["Lateral Acceleration"] = boost::python::object();
Another comment, this can be removed?

2024-04-23 13:19 UTC, Blyron commented on PythonAPI/carla/source/libcarla/V2XData.cpp
> +    // HFC["High Frequency Container Present"] = GetHFCPresentString(hfc.present);
Another comment.

2024-04-23 13:19 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.cpp
> +  // AddRecommendedValuesForSensorRoleNames(Definition);
Comment, Is this need to be removed?

2024-04-25 08:06 UTC, Blyron commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/V2X/PathLossModel.h
> +struct DiffractionObstacle
All structs inside Unreal must start with F
like
"FVector, FTransform"

2024-04-25 08:07 UTC, Blyron commented
For next time;
Inside Unreal we use CamelCase for variable and method declaration;
Classes must inherit at least from UObject to be collected by the garbage collection and their name need to start with U
Struct must start with F

2024-04-25 08:07 UTC, Blyron commented
We are gonna start minor testing soon, expect more news next week

2024-04-26 08:48 UTC, JoseM98 reviewed
Fix this compile issues, please.

2024-04-26 08:48 UTC, JoseM98 commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.h
> +  static void MakeCustomV2XDefinition(
Same, defined twice.

2024-04-26 08:48 UTC, JoseM98 commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.h
> +  static void MakeV2XDefinition(
Some methods like MakeV2XDefinition in this file are defined twice. So it gives compile errors.

2024-04-26 08:48 UTC, JoseM98 commented on Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Actor/ActorBlueprintFunctionLibrary.h
> +  static FActorDefinition MakeCustomV2XDefinition();
Same, defined twice.

2024-04-26 10:25 UTC, JoseM98 commented
Hi @grimmmbo, we have tested and everything is okay. Fix the compilation problems I mentioned you in the previous message and we will merge it. Other than that, we have detected that the framerate drops a bit when using the sensor, but it can be optimised if possible in a future update.

2024-04-29 09:19 UTC, JoseM98 commented
Hi, we have done some more tests and we believe it is working correctly. So Blyron will merge the PR soon. Things to modify for the future:
- The indentation level of CARLA is 2 spaces. In many of the files you added this is 4.
- The log level you use in the `UE_LOG(...)` macro is high. By default the "Log" category is used, e.g. `UE_LOG(LogCarla, Log, TEXT(...))`. And the "Warning" category is used only when something might be wrong or not as expected, but you always use this one.

2024-05-03 10:23 UTC, merged